# This is our top-level Makefile.  It ensures that the Makefile generated by
# qmake (i.e. Makefile.qmake-generated) gets appropriately edited with our
# desired "echo" commands in the recipes and produces the Makefile.fixed that
# we want to use.

GENERATED_FILE = Makefile.qmake-generated
FIXED_FILE     = Makefile.fixed

# Note: All top-level targets that we want to use (e.g., "make yadayada")
#       need to be added here.  If there's a specific target in the
#       generated Makefile that we want to use and it's not here to pass
#       down, then we need to call the generated Makefile directly:
#
#          make -f Makefile.fixed yadayada
#

.PHONY: default all clean

default: all

all \
clean: $(FIXED_FILE)
	@$(MAKE) -f $(FIXED_FILE) $@

$(FIXED_FILE): $(GENERATED_FILE)
	@echo ""
	@echo "===== Fixing Makefile ====="
	@echo ""
	@./FixMakefile.pl $(GENERATED_FILE) > $(FIXED_FILE)

